name: ultraball_game
description: "Ultraball - A competitive rapid chaotic sports combat game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  flutter_svg: ^2.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ui/
    - assets/ui/class_icons/
    - assets/ui/score_icons/
